# Generated by Django 5.1.4 on 2025-01-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monface', '0002_campus_cursus_job_employee_message_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='nom',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='titre',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='nom',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='job',
            name='titre',
            field=models.CharField(max_length=42),
        ),
    ]
